add_test( ChannelTest.InitialState /home/xgf/code/system-learning/cpp/week10/build-sanitize/channel_test [==[--gtest_filter=ChannelTest.InitialState]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChannelTest.InitialState PROPERTIES WORKING_DIRECTORY /home/xgf/code/system-learning/cpp/week10/build-sanitize)
add_test( ChannelTest.InterestAndReadyAreIndependent /home/xgf/code/system-learning/cpp/week10/build-sanitize/channel_test [==[--gtest_filter=ChannelTest.InterestAndReadyAreIndependent]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChannelTest.InterestAndReadyAreIndependent PROPERTIES WORKING_DIRECTORY /home/xgf/code/system-learning/cpp/week10/build-sanitize)
add_test( ChannelTest.MissingCallbackIsSkipped /home/xgf/code/system-learning/cpp/week10/build-sanitize/channel_test [==[--gtest_filter=ChannelTest.MissingCallbackIsSkipped]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChannelTest.MissingCallbackIsSkipped PROPERTIES WORKING_DIRECTORY /home/xgf/code/system-learning/cpp/week10/build-sanitize)
add_test( ChannelTest.CombinedReadWriteDispatchesBoth /home/xgf/code/system-learning/cpp/week10/build-sanitize/channel_test [==[--gtest_filter=ChannelTest.CombinedReadWriteDispatchesBoth]==] --gtest_also_run_disabled_tests)
set_tests_properties( ChannelTest.CombinedReadWriteDispatchesBoth PROPERTIES WORKING_DIRECTORY /home/xgf/code/system-learning/cpp/week10/build-sanitize)
set( channel_test_TESTS ChannelTest.InitialState ChannelTest.InterestAndReadyAreIndependent ChannelTest.MissingCallbackIsSkipped ChannelTest.CombinedReadWriteDispatchesBoth)
